In [3]:
import kmapper as km
from kmapper.jupyter import display
import umap
import sklearn
import sklearn.manifold as manifold
import numpy as np
import matplotlib.pyplot as plt

/Users/antares/.pyenv/versions/mambaforge-4.10.1-4/envs/ih_DA_env/lib/python3.9/site-packages/numba/cpython/hashing.py:524: UserWarning: FNV hashing is not implemented in Numba. See PEP 456 https://www.python.org/dev/peps/pep-0456/ for rationale over not using FNV. Numba will continue to work, but hashes for built in types will be computed using siphash24. This will permit e.g. dictionaries to continue to behave as expected, however anything relying on the value of the hash opposed to hash as a derived property is likely to not work as expected.
  warnings.warn(msg)


In [4]:

import matplotlib
import warnings

from sklearn.linear_model import SGDClassifier
from xgboost import XGBClassifier
from sklearn.svm import SVC, LinearSVC
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
warnings.filterwarnings("ignore",category=matplotlib.cbook.mplDeprecation)
warnings.filterwarnings("ignore", category=UserWarning)
_ = np.seterr(over='ignore')
#from pretty_confusion_matrix import plot_confusion_matrix_from_data as conf_matrix
warnings.simplefilter(action='ignore', category=FutureWarning)

from heist_tools import *


/Users/antares/.pyenv/versions/mambaforge-4.10.1-4/envs/ih_DA_env/lib/python3.9/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index


In [84]:
dft = pd.read_csv('dft.csv')

In [85]:
dft.n_day.min()

1

In [86]:
# initialize mapper
mapper = km.KeplerMapper(verbose=1)

KeplerMapper(verbose=1)


In [87]:
dft.label.value_counts()

white                  345060
CryptoWall               1476
CryptoLocker             1144
Cerber                   1083
Locky                     785
CryptXXX                  293
DMALockerv3                51
NoobCrypt                  45
DMALocker                  26
SamSam                     11
Globe                       7
CryptoTorLocker2015         5
GlobeImposter               5
WannaCry                    2
VenusLocker                 2
CryptConsole                2
Sam                         1
Flyper                      1
APT                         1
XLocker                     1
EDA2                        1
JigSaw                      1
Razy                        1
Name: label, dtype: int64

In [92]:
dft_CW = dft[(dft['label']=='CryptoWall')|(dft['label']=='CryptoLocker')]

In [99]:
graph_fs = ['length', 'weight', 'count', 'neighbors','looped',
            'income']

In [100]:
dft_CW=dft_CW[graph_fs].reset_index(drop=True)

In [101]:
dft_CW

length    weight  count  neighbors  looped        income
0          2  3.000000      3          3       0  1.160000e+09
1        144  0.601246   1482          2    1477  2.180967e+08
2         14  1.049479     18          3       0  2.580000e+08
3         22  0.025000     13          1       0  5.332900e+07
4          6  1.000000      1          2       0  1.000000e+08
...      ...       ...    ...        ...     ...           ...
2615       6  0.100000      1          1       0  3.180000e+08
2616      10  0.104167      4          1       4  2.224397e+08
2617     144  1.771798   2744          6    2744  7.813000e+08
2618       0  1.000000      1          1       0  3.799540e+09
2619       0  0.500000      1          1       0  5.756717e+08

[2620 rows x 6 columns]

In [102]:
from sklearn.preprocessing import StandardScaler

In [103]:
scaler = StandardScaler()

In [104]:
scaler.fit(dft_CW)

StandardScaler()

In [105]:
dft_CW = scaler.transform(dft_CW)

In [106]:
dft_CW

array([[-0.67348818,  1.83374873, -0.43360267,  0.2071489 , -0.23949826,
        -0.00822817],
       [ 1.77457872, -0.16509431,  1.33867411, -0.1289069 ,  2.99076907,
        -0.10678478],
       [-0.46660929,  0.20841114, -0.41562826,  0.2071489 , -0.23949826,
        -0.10260948],
       ...,
       [ 1.77457872,  0.81030765,  2.85092111,  1.21531628,  5.76175669,
        -0.04785367],
       [-0.707968  ,  0.16718095, -0.43599926, -0.46496269, -0.23949826,
         0.26796166],
       [-0.707968  , -0.249461  , -0.43599926, -0.46496269, -0.23949826,
        -0.06936971]])

In [108]:
# project data into 2D subsapce via 2 step transformation, 1)isomap 2)UMAP
projected_data = mapper.fit_transform(dft_CW, projection=[manifold.Isomap(n_components=6, n_jobs=-1), umap.UMAP(n_components=2,random_state=1)])

..Composing projection pipeline of length 2:
	Projections: Isomap(n_components=6, n_jobs=-1)
		UMAP(random_state=1)
	Distance matrices: False
False
	Scalers: MinMaxScaler()
MinMaxScaler()
..Projecting on data shaped (2620, 6)

..Projecting data using: 
	Isomap(n_components=6, n_jobs=-1)



/Users/antares/.pyenv/versions/mambaforge-4.10.1-4/envs/ih_DA_env/lib/python3.9/site-packages/scipy/sparse/_index.py:103: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_intXint(row, col, x.flat[0])
/Users/antares/.pyenv/versions/mambaforge-4.10.1-4/envs/ih_DA_env/lib/python3.9/site-packages/scipy/sparse/_index.py:103: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_intXint(row, col, x.flat[0])
/Users/antares/.pyenv/versions/mambaforge-4.10.1-4/envs/ih_DA_env/lib/python3.9/site-packages/scipy/sparse/_index.py:103: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_intXint(row, col, x.flat[0])
/Users/antares/.pyenv/versions/mambaforge-4.10.1-4/envs/ih_DA_env/lib/python3.9/site-packages/scipy/sparse/_index.py:103: SparseEfficiencyWarning: Changing the 


..Scaling with: MinMaxScaler()

..Projecting on data shaped (2620, 6)

..Projecting data using: 
	UMAP(random_state=1, verbose=1)

UMAP(random_state=1, verbose=1)
Wed Dec 21 19:03:57 2022 Construct fuzzy simplicial set
Wed Dec 21 19:03:58 2022 Finding Nearest Neighbors
Wed Dec 21 19:03:58 2022 Finished Nearest Neighbor Search
Wed Dec 21 19:03:58 2022 Construct embedding


Epochs completed:   0%|            0/500 [00:00]

Wed Dec 21 19:04:01 2022 Finished embedding

..Scaling with: MinMaxScaler()



In [115]:

G = mapper.map(projected_data, dft_CW, clusterer=sklearn.cluster.DBSCAN(metric="cosine"))

Mapping on data shaped (2620, 6) using lens shaped (2620, 2)

Creating 100 hypercubes.

Created 49 edges and 51 nodes in 0:00:00.042434.


In [116]:
# define an excessively long filename (helpful if saving multiple Mapper variants for single dataset)
fileID = 'projection=' + G['meta_data']['projection'].split('(')[0] + '_' + \
'n_cubes=' + str(G['meta_data']['n_cubes']) + '_' + \
'perc_overlap=' + str(G['meta_data']['perc_overlap']) + '_' + \
'clusterer=' + G['meta_data']['clusterer'].split('(')[0] + '_' + \
'scaler=' + G['meta_data']['scaler'].split('(')[0]

In [117]:
# visualize graph
mapper.visualize(G,
                path_html="mapper_example_" + fileID + ".html",
                title=fileID,
             #   custom_tooltips = np.arange(len(graph_fs)),
                #color_values = dft_CW['length'].to_numpy(),
                color_function_name = 'Length',
                node_color_function = np.array(['average', 'std', 'sum', 'max', 'min']))

# display mapper in jupyter
km.jupyter.display("mapper_example_2" + fileID + ".html")

Wrote visualization to: mapper_example_projection=UMAP_n_cubes=10_perc_overlap=0.1_clusterer=DBSCAN_scaler=MinMaxScaler.html


/Users/antares/.pyenv/versions/mambaforge-4.10.1-4/envs/ih_DA_env/lib/python3.9/site-packages/kmapper/visuals.py:344: RuntimeWarning: invalid value encountered in long_scalars
  height = np.floor(((bar / max_bucket_value) * 100) + 0.5)
/Users/antares/.pyenv/versions/mambaforge-4.10.1-4/envs/ih_DA_env/lib/python3.9/site-packages/kmapper/visuals.py:345: RuntimeWarning: invalid value encountered in long_scalars
  perc = round((bar / sum_bucket_value) * 100.0, 1)


'<!DOCTYPE html>\n<html>\n\n<head>\n  <meta charset="utf-8">\n  <meta name="generator" content="KeplerMapper">\n  <title>projection=UMAP_n_cubes=10_perc_overlap=0.1_clusterer=DBSCAN_scaler=MinMaxScaler | KeplerMapper</title>\n\n  <link rel="icon" type="image/png" href="http://i.imgur.com/axOG6GJ.jpg" />\n\n  <link href=\'https://fonts.googleapis.com/css?family=Roboto+Mono:700,300\' rel=\'stylesheet\' type=\'text/css\'>\n  <style>* {\n  margin: 0;\n  padding: 0;\n}\n\nhtml, body {\n  height: 100%;\n}\n\nbody {\n  font-family: "Roboto Mono", "Helvetica", sans-serif;\n  font-size: 14px;\n}\n\n#logo {\n  width:  85px;\n  height: 85px;\n}\n\n#display {\n  color: #95A5A6;\n  background: #212121;\n}\n\n#header {\n  background: #111111;\n}\n\n#print {\n  color: #000;\n  background: #FFF;\n}\n\nh1 {\n  font-size: 21px;\n  font-weight: 300;\n  font-weight: 300;\n}\n\nh2 {\n  font-size: 18px;\n  padding-bottom: 20px;\n  font-weight: 300;\n}\n\nh3 {\n  font-size: 14px;\n  font-weight: 700;\n  text

In [112]:
dft_CW[16,:]

array([ 1.77457872, -0.63245281,  2.36441375, -0.46496269, -0.23949826,
       -0.10867834])

In [113]:
dft_CW

array([[-0.67348818,  1.83374873, -0.43360267,  0.2071489 , -0.23949826,
        -0.00822817],
       [ 1.77457872, -0.16509431,  1.33867411, -0.1289069 ,  2.99076907,
        -0.10678478],
       [-0.46660929,  0.20841114, -0.41562826,  0.2071489 , -0.23949826,
        -0.10260948],
       ...,
       [ 1.77457872,  0.81030765,  2.85092111,  1.21531628,  5.76175669,
        -0.04785367],
       [-0.707968  ,  0.16718095, -0.43599926, -0.46496269, -0.23949826,
         0.26796166],
       [-0.707968  , -0.249461  , -0.43599926, -0.46496269, -0.23949826,
        -0.06936971]])